version:  '3'
services:
  notebooks:
    build:
      dockerfile: Dockerfile 
      context: .
    image: tiledb-foss4g
    volumes:
      - ./notebooks:/home/jovyan/work
      - ../data:/home/jovyan/data   
    ports:
      - 8888:8888
    container_name: tiledb_foss4g
    command: "start-notebook.sh"
