name: tiledb-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - pyarrow
  - pandas
  - numpy
  - tiledb-py
  - jupyterlab
  - matplotlib
  - rasterio
  - jq
  - pdal
  - geopandas
  - sparse
  - netcdf4
  - xarray
  - cartopy
  - awscli
  - pip 
  - pip:
    - tiledb-cf
